/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDialog: typeof import('./../components/dialog/AddDialog.vue')['default']
    AppBreadCrumb: typeof import('./../components/layout/AppBreadCrumb.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./../components/layout/AppLayout.vue')['default']
    AppParentView: typeof import('./../components/layout/AppParentView.vue')['default']
    AppRouterView: typeof import('./../components/layout/AppRouterView.vue')['default']
    AppSideMenu: typeof import('./../components/layout/AppSideMenu.vue')['default']
    AppSideMenuBak: typeof import('./../components/layout/AppSideMenuBak.vue')['default']
    EditDialog: typeof import('./../components/dialog/EditDialog.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormColumn: typeof import('element-plus/es')['ElFormColumn']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTreeSelect: typeof import('element-plus/es')['ElTreeSelect']
    FormDialog: typeof import('./../components/dialog/FormDialog.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Icon: typeof import('./../components/icon/Icon.vue')['default']
    IconPicker: typeof import('./../components/icon/IconPicker.vue')['default']
    IconPickerGrid: typeof import('./../components/icon/IconPickerGrid.vue')['default']
    InfoBar: typeof import('./../components/chart/InfoBar.vue')['default']
    KlineChart: typeof import('./../components/chart/KlineChart.vue')['default']
    MacdChart: typeof import('./../components/chart/MacdChart.vue')['default']
    MenuIcon: typeof import('./../components/icon/MenuIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideMenuItem: typeof import('./../components/layout/SideMenuItem.vue')['default']
    SideMenuItemBak: typeof import('./../components/layout/SideMenuItemBak.vue')['default']
    ThemeSettings: typeof import('./../components/theme-settings/ThemeSettings.vue')['default']
    ThemeSwitch: typeof import('./../components/theme-switch/ThemeSwitch.vue')['default']
    ThemeSwitcher: typeof import('./../components/theme-switcher/ThemeSwitcher.vue')['default']
    Toolbar: typeof import('./../components/chart/Toolbar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
